#!/data/data/com.termux/files/usr/bin/env bash

ssh -o ConnectTimeout=5 -o BatchMode=yes -o StrictHostKeyChecking=no x220 "export PANELFIFO=\"/tmp/panel-fifo\"; export DISPLAY=\":0\"; ~/.Scripts/lock_keys"
