#!/usr/bin/env bash
# Prokrastimer - pomodoro timer
# made to prevent its own creation

clean() {
	[[ "${FUNCNAME[1]}" = "timer" || $1 ]] || return
	printf '\e[2J\e[H\e[1;34m%s\n' "$logo"
	read -r height width < <(stty size)
	((width-=2))
}

bar() {
	printf -v elaps "%$(($1*width/s[c]))s"
	printf -v total "%$((width-($1*width/s[c])))s"
   printf '\e[J\e[999;0H%s\r' "[${elaps// /\#}${total// /-}]"
}

prompt() { clean force
   read -rp $'\e[10;0H\e[1;37m'"work in min. (25): "$'\e[m' work
   read -rp $'\e[1;37m'"breaks in min. (5): "$'\e[m' break
   read -rp $'\e[1;37m'"number of sessions (3): "$'\e[m' ss
	((work=work?work*60:1500,break=break?break*60:300,ss=ss?ss*2:6))
}

state_done() {
   play "$HOME/.bin/.prokrastimer/gong.wav" 2>/dev/null &
   printf '\e[10;0H\e[J\e[1;39m%s' "${s[c]} completed"
	notify-send "$_" 2>/dev/null
	((c=c?0:1,ct=c?ct:ct++))
}

next_state() {
   read -rp $'\e[11;0H\e[1;33m'"press ENTER to start ${s[c]}"$'\r'
}

completed() {
	((total=(ct*work)+work-sec+30))
	printf '\e[7;0H\e[J\e[1;33m%s%2dh%2dm\e[?25h\n'\
		"combined time worked:" "$((total/60/60))" "$((total/60%60))"
	echo $ct
}

timer() { clean force
	for ((sec=s[c],st=SECONDS;sec>0;sec=(s[c]-(SECONDS-st)))){
      printf '\e[?25l\e[10;0H\e[1;35m%s%02d:%02d'\
			"${s[c]^} left: " "$((sec/60))" "$((sec%60))"
      bar $((SECONDS-st))
		sleep 1
	}
	state_done
}

main() {
	logo=$(figlet prokrastimer) # change this
	s=( "work" "break" )

   prompt; traps
   for ((i=2;;i++)){ timer; ((i<ss)) && next_state; }
}

traps(){
   trap "completed; stty echo" EXIT
	trap "printf '\e[A';exit" SIGINT
	trap 'clean' SIGWINCH
	stty -echo
}

main
