#!/usr/bin/env bash

loop() { for ((;;)){ timer; printf '%s\e[1A' "press [ENTER] to restart"; read;};}

usage() { printf '\e[0;34m%s%s\n' "Usage: $(basename $0) "\
      "[-l <opt>] [<number>m|s] [<min>:<sec>]"; }

check() {
   case $1 in
      *[0-9]':'[0-9][0-9]) IFS=':' read -r -a k <<< "$1"
	 ((m=${k[0]},s=${k[1]},l=(m*60)+s)) ;;
      *[0-9]'m') ((l=${1%m}*60)) ;;
      *[0-9]'s') ((l=${1%s})) ;;
      *) printf '%s\n%s\n' "unknown option '$1'" "timer -h for help"; exit 1
   esac

   [[ $l ]] && l="$l-"
}

timer() { 
   stty -echo; st=$(date +%s)
   for ((;;)){
      ((c=$(date +%s),s=$l(c-st)))
      printf '\e[?25l\e[1;34m\r\e[J%02d:%02d' "$((s/60))" "$((s%60))"
      ((s<0)) && printf '\r%s\n' "times up!" && break; sleep 1
   }
   dunstify "" "<b>timer done</b>"
   beep
}

beep() { for ((i=0;i<3;i++)){ env -i beep &>/dev/null || sudo env -i beep;((;:;));}; }

main() {
   trap "stty echo; printf '\e[J\e[?25h'" EXIT
   while getopts ":l:h" o; do case "${o}" in
      l) shift; check $OPTARG; loop ;;
      h) usage; exit 0 ;;
   esac; done
   [[ $1 ]] && check $1; timer
}

main "$@"
