#!/usr/bin/env bash

coproc acpi_listen
trap 'kill $COPROC_PID' EXIT

notify_plugged(){ [[ $1 = *ACPI* ]] && dunstbar -o; }

power_menu(){ [[ $1 = "PBTN" ]] && st -c float -g 30x5+600-10 -e bye; }

handler(){
   case "$1" in
      button/power) power_menu $2 ;;
      button/screenlock) lock_keys ;;
      ac_adapter) notify_plugged $2 ;;
      button/prog1|button/suspend) lockscreen ;;
   esac
}

while read -u "${COPROC[0]}" -a event; do
   handler "${event[@]}"
done
