#!/bin/sh

logic(){
   W=$(bspc query -N -n .local.tiled | wc -l)
   [ "$W" -le 1 ] && W=1
   G=$(((GN-W)*GS)); $((G-=GO))
   [ "$G" -le "$GO" ] && G="$GO"
   P=$(((PN-W)*PS*10)); [ "$P" -le 5 ] && P=0
}

exec_(){
   for s in left right;do
      bspc config -d focused ${s}_padding "$P" &
   done &
   bspc config -d focused window_gap "$G"
}

main(){
   while read -r _; do
      xprop="$(xprop -root _NET_CURRENT_DESKTOP)"
      case "${xprop##*= }" in
         9) P=0; G=0; exec_
            ;;
         *) logic; exec_
      esac
      #[ "$W" -lt "2" ] && sp="0.60" || sp="0.5"
      #bspc config split_ratio "$sp"
   done < "$GAPFIFO"
}

main
