#!/bin/bash

trap 'exit_protocol' EXIT

exit_protocol(){
	for desktop in {1..10}; do
		for side in left right; do
			bspc config -d $desktop ${side}_padding 0
		done
		bspc config -d $desktop window_gap 10
	done
}

main(){

	W=$(bspc query -N -n .local.\!hidden.tiled | wc -l); [ "$W" -le 1 ] && W=1
	$((P=((PN-W)*PS*10)*PADD))
	$((G=((GN+1-W)*GS)*GAPS))
	[ "$P" -le 0 ] && P=0
	[ "$G" -le "$((G0))" ] && G="$G0"
	for s in left right;do
		bspc config -d focused ${s}_padding "$P" &
	done & bspc config -d focused window_gap "$G"
}

[[ -e "$GAPFIFO" ]] && rm "$GAPFIFO"
mkfifo "$GAPFIFO"
bspc subscribe node_add node_remove desktop_focus > $GAPFIFO &

while read -r _; do main; done < "$GAPFIFO"
