#!/usr/bin/env bash

case_event(){
   case $1 in
      node_add) swallow "${evt[4]}" ;;
      node_remove) spit "${evt[3]}" ;;
   esac
}

swallow() {
   query_desktop || return
   query_swallower "$1" || return
   query_swallowing || return
   hide_node
}

spit() {
   query_spitter "$1" || return
   query_spitting_desktop || pull_node_desktop
   show_node
}

query_desktop(){
   last_desktop=$(bspc query -D -n last)
   [[ "$desktop" = "$last_desktop" ]] || false
}

query_swallower(){
   swallower=$(probe $1)
   read -r do_swallow <"$HOME/.config/bspwm/swallow"
   [[ "$do_swallow" =~ $swallower ]] || false
}

probe(){
   xprop -id "$1" |\
      sed -n '/WM_CLASS\|WM_COMMAND/s/.*"\(.*\)".*/\1/p'
}
query_swallowing(){
   swallowing=$(probe "$1")
   [[ "$swallowing" = "St" ]] || false
}

query_spitter(){
   spitter=$1
   grep "^$spitter" "$swallowed" || false
}

query_spitting_desktop(){
   spitting=$(grep "^$spitter" "$swallowed" |\
      head -n1 | awk '{print $2}')
   spitting_desktop=$(bspc query -D -n "$spitting")
   [[ "$spitting_desktop" = "$desktop" ]] || false
}

hide_node(){
   bspc node "$swallowing" --flag hidden=on &&
      echo "$swallower $swallowing" >> "$swallowed"
}

show_node(){
   bspc node "$spitting" --flag hidden=off
   bspc node "$spitting" -f
   sed -i "/^$spitter/d" "$swallowed"
}

pull_node_desktop(){
   bspc node "$spitting" -d "$spitting_desktop"
}

main(){
   bspc subscribe node_add node_remove |
   while read -r -a evt; do
      swallowed="/tmp/swallowed"
      desktop="${evt[2]}"
      case_event "${evt[0]}"
   done
}

main
