#!/usr/bin/env bash

case_event(){
	case $1 in
		node_add) swallow ;;
		node_remove) spit ;;
	esac
}

swallow() {
	query_desktop || return 1
	query_swallower || return 1
	query_swallowing || return 1
	hide_node
}

spit() {
	get_spitting
	query_spitting_desktop || pull_node_desktop
	show_node
}

query_desktop(){
	last_desktop=$(bspc query -D -n last)
	[[ "$desktop" = "$last_desktop" ]] || false
}

query_swallower(){
	do_swallow="Sxiv Zathura"
	[[ "$do_swallow" =~ $(probe "$node_added") ]] || false
}

query_swallowing(){
	[[ $(probe "$node_swallow") = "St" ]] || false
}

hide_node(){
	bspc node "$node_swallow" --flag hidden=on
	swallowed+=("$node_added $node_swallow")
	echo ${swallowed[@]}
}

query_spitting_desktop(){
	spitting_desktop=$(bspc query -D -n "$node_spit")
	[[ "$spitting_desktop" = "$desktop" ]] || false
}

get_spitting(){
	for node in "${swallowed[@]}"; do
		[[ "$node" =~ ^$node_removed ]] || continue
		set $node; node_spit="$2"
	done
}

show_node(){
	bspc node "$node_spit" --flag hidden=off
	bspc node "$node_spit" -f
	unset 'swallowed[i]'
}

pull_node_desktop(){
	bspc node "$node_spit" -d "$desktop"
}

probe(){
	xprop -id "$1" | sed -n '/WM_CLASS\|WM_COMMAND/s/.*"\(.*\)".*/\1/p'
}

define_events(){
	node_swallow="$4"
	node_added="$5"
	node_removed="$4"
	desktop="$3"
}

main(){
	while read -r -a evt; do
		define_events "${evt[@]}"
		case_event "${evt[0]}"
		echo > $GAPFIFO
	done < <(bspc subscribe node_add node_remove)
}

main
