#!/usr/bin/env bash

mk_tmp(){
	# echo creating tmp file
	tmp="$(mktemp)"
}

get_files(){
	# echo testing names
	for name in "$@"; do
		[[ -a $name ]] && { old_names+=("${name}"); continue; }
		printf '%s\n' "Does not exist: '$name'"
		exit 1
	done
	path="${old_names[0]%\/*}"
}

write_tmp(){
	# echo writing names to file
	printf '%s\n' "${old_names[@]##*\/}" > $tmp
}

read_new_names(){
	# echo reading new names
	IFS=$'\n' read -d '' -ra new_names < "$tmp"
}

check_new_names(){
	# echo checking new filenames
	(( ${#old_names[@]}==${#new_names[@]} )) || { printf '\n%s\n' "dont delete lines"; exit 1; }
}

move_files(){
	# echo moving files
	for((i=0;i<${#new_names[@]};i++));{
		[[ "${old_names[i]}" = "${path}/${new_names[i]}" ]] && continue
		mv "${old_names[i]}" "${path}/${new_names[i]}" &&
			echo mv "${old_names[i]##*\/}" "${new_names[i]}"
	}
}

rm_tmp(){
	# echo removing tmp file
	rm $tmp
}

mk_tmp
get_files "$@"
write_tmp
nvim "$tmp"
read_new_names
check_new_names
move_files
rm_tmp
