#!/usr/bin/env bash

dir="$HOME/Pictures/favoritter"

usage(){ printf '%s\n' "chwal [-rl] [-f '/path/to/image']" "-r: reload current" "-l: light theme" "-f: add image to rotation"; }

sel(){
   current=$(awk -F/ 'NF>1{print $NF}' $HOME/.cache/wal/wal)
   files=$(ls $dir | sed '/.backend/d')

   get_next_fav || next="$dir/$current"

   backend="$(cat "${next%.*}.backend")"

   wal -tqi $next ${l} --backend $backend -a 0

   cp $next "$HOME/.config/wall.png"

   $CONFIG &>/dev/null
}

get_next_fav(){
	[[ $r = "1" ]] && return 1

   [[ $(printf "$files\n" | tail -1) = ${current} || -z $(echo $files | grep $current) ]] &&
      next="$dir/$(printf '%s' "$files" | head -1)" ||
      next="$dir/$(printf '%s' "$files" | awk "/$current/{getline; print}")"
}

fav(){
   trap 'printf "\n"' EXIT

   printf '\e[H\e[2J\e[1;34m%s\n\e[0;34m%s\n%s\n%s\n%s\n\e[1;32m%s\e[0m'\
      "backends:"\
		"w: wal"\
		"c: colorz"\
		"h: haishoku"\
		"t: colorthief"\
		"choose > "

   read -r; [[ ! $REPLY ]] && exit
   case $REPLY in
		w) backend="wal" ;;
		c) backend="colorz" ;;
      h) backend="haishoku" ;;
		t) backend="colorthief" ;;
		*) exit 1
   esac

   [[ $backend ]] && {
		name="${1##*/}"
		echo $name
		printf '%s' "$backend" > "$dir/${name%.*}.backend"
   	cp "$1" "$dir/${1##*/}"
	}
	exit 0
}

main(){
	while getopts "rlf:" o; do case $o in
         f) [[ $OPTARG ]] && fav $OPTARG ;;
			l) l="-l" ;;
			r) r="1" ;;
			*) usage; exit 1
		esac
	done
   sel "$@"
}

main "$@"
