#!/usr/bin/env bash

dot(){
   #echo "${op[@]}"
   git "${op[@]}"
}

o=(--git-dir=$HOME/.dotfiles/ --work-tree=$HOME)

case $1 in 
   up)
      op=(${o[@]} commit -a -m from_script); dot
      op=(${o[@]} push -u origin master); dot
         ;;
   *) [[ "$@" ]] && op=(${o[@]})
esac
