#!/usr/bin/env bash

git_do(){
	git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
}

commit(){
	git_do commit -am "$changes"
}

push(){
	[[ $changes ]] && commit
	git_do push
}

case_opts(){ 
	case $1 in up) push ;; *) git_do "$@"; esac
}

print_status(){
   changes=$(git_do status --porcelain)
   [[ -z "$1" && ! -z $changes ]] && printf '%s\n' "$changes"
}

print_status "$1"
[[ $1 ]] || exit
case_opts "$@"
