#!/usr/bin/env bash

git_do(){
	git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
}

commit(){
	readme="$HOME/README.md"
	cp $HOME/.dotfiles/README.md $readme
	git_do add $HOME/README.md
	[[ "$message" ]] || message="$changes"
	git_do commit -am "$message"
	rm $readme
	git update-index --assume-unchanged $readme
}

push(){
	[[ $changes ]] && commit
	git_do push
}

case_opts(){ 
	case $1 in
		up) shift; message="$@"; push ;;
		*) git_do "$@"
	esac
}

print_status(){
   changes=$(git_do status --porcelain)
   [[ -z "$1" && ! -z $changes ]] && printf '%s\n' "$changes"
}

print_status "$1"


[[ $1 ]] || exit
case_opts "$@"
