#!/usr/bin/env bash

main(){
   get_size
   query_min_size || return
   st -c "float" -g ${W}x${H}+${X}+${Y}
}

prompt_draw(){
   slop -f "%x %y %w %h" -b 2 -t 0 -q
}

get_size(){
   read -r X Y W H < <(prompt_draw)
   (( W/=1366/192, W-=3, H/=768/49, H-- ))
}

query_min_size(){
   (( W>=10 && H>=1 )) || false
}

main
