#!/usr/bin/env bash

loop(){ sleep 1.2; for ((;;)){ barnot -o;sleep 10;}; }

kill_loop(){
   #kill -9 "$loop"
   dunstify -C 90211
}

bar(){
   #while read -r event; do
      w=$(bspc query -N -n .local.\!hidden.window)
   #   ((w<=0)) && loop & loop="$!"
   #   [[ "$event" =~ remove ]] || kill_loop
   #   [[ "$event" =~ focus ]] && print_ws
   #done < "$BARFIFO"
}

barnot(){
   case $1 in
      -c) get_stats; out=("$mem $cpu $temp") ;;
      -d) get_date; out=("$dy, $d" "<b>($dt)</b>") ;;
      -b) out=( "$(light | awk -F"." '{print $1}')%") ;;
      -v) get_volume && out=(" ($volume)") || out=(" $volume ") ;;
		-w) print_ws ;;
      -o) get_bat; get_net
	  out=("" "$bat | $net | <b>$(date '+%R')</b>") || exit 1
   esac

   dunstify "${out[@]}" -t "$t" -r 90211
}

get_stats(){
   mem="[mem] $(free -h | awk '/Mem:/ {print $3 "/" $2}')"
   temp="[temp]$(acpi -t | sed 's/Thermal 0: ok,//g' |\
      awk -F . '{print $1}')°C"
   cpu="[cpu] $(mpstat | grep all | awk '{print $3}' |\
      awk -F"," '{print $1}')%"
}

get_volume(){
   volume="$(pamixer --get-volume)%"
   [[ $(pamixer --get-mute) = "true" ]]
}

get_date(){
   d=$(date +%d" "%B)
   dy=$(date +%A)
   dt=$(date +%d/%m/%y)
}

get_net(){
   st="$(nmcli | awk '/wlp3s0/ {print $4}')"
   inf="$(networkctl status | awk '/Addr/ {print $2}')"
   sn="no connection"
   [[ "$inf" ]] && {
      sn=$(iwlist wlp3s0 scan | sed -n '5P' | awk -F'=' '{print $3}' | awk -F' ' '{print $1}')
      ((sn>-20)) && i=""
      ((sn<-20)) && i=""
      ((sn<-45)) && i=""
      ((sn<-60)) && i=""
   }
   net=" <b>$st</b> <b>[$sn]</b>"
}

get_bat(){
   read -r p < "/sys/class/power_supply/BAT0/capacity"
   read -r s < "/sys/class/power_supply/AC/online"
   case $s in
      1) l="" ;;
      0)
	 ((p>=80)) && l=""
	 ((p<=80)) && l=""
	 ((p<=65)) && l=""
	 ((p<=40)) && l=""
	 ((p<=20)) && l=""
	 ;;
      *) l=""
   esac; bat="$l <b>$p%</b>"
}

print_ws(){
   ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3+1}')
   dunstify -C 90210; sleep .01; dunstify "$ws" -t 1250 -r 90211
}

[[ "$1" ]] && { t=5000; barnot "$1"; exit; } || { t=11000; bar; }
