#!/usr/bin/env bash

getext(){
   case ${1##*.} in
      zip) _zip $1 ;;
      .tar.bz|.tar.bz2|.tbz|.tbz2) tar xjvf $f;;
      .tar.gz|.tgz) tar xzvf $f;;
      .tar.xz|.txz) tar xJvf $f;;
      .rar) unrar x $f;;
      .7z) 7z x $f;;
      *) printf '%s\n' "\".${1##*.}\" not supported" ;;
   esac
}

confirm(){
   read -r -p "Unpack \"$1\" [Y/n]: "
   [[ "$REPLY" = "n" ]] && false
}

_zip(){
   unzip -Z -h $1 
   confirm $1 || exit
   unzip -x $1 -d "${1%.*}/"
}

main(){
   [[ -z $1 ]] && { printf '%s\n' "Usage: extract \"example.ext\""; exit; }
   [[ -f $1 ]] && getext $1 || printf '%s\n' "Not a file"
}

main "$@"
