#!/usr/bin/env bash

net(){
   st="$(nmcli | sed -n "1s/.*: //p")"
   inf="$(networkctl status | grep Address |\
      sed -n 's/Address://g;s/  *//g; s/on/ /g; P; Q' | awk '{print $2}')"
   [[ "$st" = "tilsluttet"* && "$inf" = "wlp3s0" ]] && {
      sn=$(iwlist wlp3s0 scan | sed -n '5P' | awk -F'=' '{print $3}' | awk -F' ' '{print $1}')
      ((sn>-20)) && i="****"
      ((sn<-20)) && i="***"
      ((sn<-45)) && i="**"
      ((sn<-60)) && i="*"
   }
   net="$st $sn"
}

bat(){
   p="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $4}')"
   s="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $3}')"
   case $s in
      Charging) l="[chr]" ;;
      Unknown) l="[unkn]" ;;
      Full) l="[fll]" ;;
      Discharging) l="[dis]" ;;
      *) l="[error]"
   esac; bat="$l $p%"
}

barnot(){
   case $1 in
      -c)
	 mem="[mem] $(free -h | awk '/Mem:/ {print $3 "/" $2}')"
	 temp="[temp]$(acpi -t | sed 's/Thermal 0: ok,//g' | awk -F . '{print $1}')°C"
	 cpu="[cpu] $(mpstat | grep all | awk '{print $3}' | awk -F"," '{print $1}')%"
	 out=("$mem $cpu $temp") ;;
      -d)
	 d=$(date +%d" "%B);dy=$(date +%A);dt=$(date +%d/%m/%y)
	 out=("$dy, $d" "($dt)") ;;
      -b)
	 out="[bakl] $(light | awk -F"." '{print $1}')%" ;;
      -v)
	 volume="$(pamixer --get-volume)%"
	 [[ $(pamixer --get-mute) = "true" ]] && out=("[vol] ($volume)") || out=("[vol] $volume ") ;;
      *)
	 bat; net; out=("" "$bat | $net | $(date '+%R')") || exit 1
   esac
   pkill -SIGUSR1 herbe
   herbe "${out[@]}"
}

bar(){
   while read -r line; do
      w=$(bspc query -N -n .local.\!floating | wc -l)
      [[ "$line" != *remove* ]] && { echo hej; kill -9 "$loop"; pkill -SIGUSR 1 herbe; }
      ((w<=0)) && sleep 1.2 && loop & loop="$!"

      [[ "$line" = *focus* ]] && {
	 ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3+1}')
	 pkill -SIGUSR 1 herbe; ((;:;)); herbe "$ws "
      }
   done < "$BARFIFO"
}

loop(){ for ((;;)){ barnot;sleep 10;}; }

main(){
   w=$(bspc query -N -n .local.\!floating | wc -l)
   case $1 in "--boot")
	 t=11000; bar ;;
      *) t=5000; barnot "$1"
   esac
}

main "$@"
