#!/usr/bin/env bash
bac="$HOME/.back_history"
his="$HOME/.bash_history"

found_backup(){
	read -rsn1 -p "Found old backup file, please remove before continuing."$'\n'"Press any key... "; echo
	exit 1
}

[[ -a $bac ]] && found_backup

cp $his $bac
cat "$bac" | nl | sort -k 2 | uniq -f 1 | sort -n | cut -f 2 > "$his"
