#!/usr/bin/env bash

case_opt(){
   case $1 in
      -c) get_stats; out=("$mem $cpu $temp") ;;
      -d) get_date; out=("$dy, $d" "<b>($dt)</b>") ;;
      -b) out=( "$(light | awk -F"." '{print $1}')%") ;;
      -v) get_volume && out=(" ($volume)") || out=(" $volume ") ;;
		-w) ws ;;
      -o) get_bat; get_net; get_date; out=("" "$bat | $net | $hm") || exit 1
   esac
	print_bar
}

ws() {
   s=($(xprop -root _NET_DESKTOP_NAMES | awk '{$1=$2=""; print $0}' |\
      sed -e 's/,//g' -e 's/\"//g' -e 's/^[[:space:]]*//'))
   c=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
   
   for ((i=0;i<${#s[*]};i++)){ 
      [[ "$i" = "$c" ]] && s[$i]="%{F#0f0}[${s[$i]}]%{B-}%{F-}" ||
	 s[$i]="${s[$i]}"
   }
   
   export W="$(sed -e 's/\(}\).?\(%\)/\1\2/' <<< "${s[*]}")"
}

parse(){
	ws; net; rest
   printf '%s\n' "  $W %{r}| updates: $U | free: /${R} /home${H} | $B | $N | $D | "
}

print_bar(){
	parse | lemonbar -p ${opt[@]}\
   -g 1366x20\
   -f "ypn envypn:size=10"\
   -o 1 -b\
   -B "$background"\
   -F "$foreground"\
   -u 2 | while read -r line; do eval "$line"; done
		echo done
}

get_stats(){
   mem="[mem] $(free -h | awk '/Mem:/ {print $3 "/" $2}')"
   temp="[temp]$(acpi -t | sed 's/Thermal 0: ok,//g' |\
      awk -F . '{print $1}')°C"
   cpu="[cpu] $(mpstat | grep all | awk '{print $3}' |\
      awk -F"," '{print $1}')%"
}

get_volume(){
   volume="$(pamixer --get-volume)%"
   [[ $(pamixer --get-mute) = "true" ]]
}

get_date(){
   d=$(date +%d" "%B)
   dy=$(date +%A)
   dt=$(date +%d/%m/%y)
	hm=$(date +%R)
}

get_ip(){ wlp=0 
	while read -r line; do
		[[ $line =~ ^wlp3s0 ]] && wlp="1"
		[[ $wlp == 1 ]] || continue

		[[ $line =~ .*inet.*  ]] || continue
		set $line; ip=$2; break
	done < <(ifconfig)
}

get_net(){
	st="$(iwgetid -r)"
   inf="$(networkctl status | awk '/Addr/ {print $2}')"
	#vpn="$(expressvpn status | sed -n 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g;1P')"
   sn="no connection"
   [[ "$inf" ]] && {
      sn=" $(iwlist wlp3s0 scan | sed -n '5P' | awk -F'=' '{print $3}' | awk -F' ' '{print $1}')"
		get_ip
		#vpn=" |  ${vpn%\ -*}"
      ((sn>-20)) && i="****"
      ((sn<-20)) && i="***"
      ((sn<-45)) && i="**"
      ((sn<-60)) && i="*"
   }
   #net=" <b>$st</b> <b>[$sn]</b>"
	#net=" ${st}${sn} (${ip})${vpn}"
	net=" ${st}${sn} (${ip})"
}

get_bat(){
   read -r p < "/sys/class/power_supply/BAT0/capacity"
   read -r s < "/sys/class/power_supply/AC/online"
   case $s in
      1) l="" ;;
      0)
			((p>=80)) && l=""
			((p<=80)) && l=""
			((p<=65)) && l=""
			((p<=40)) && l=""
			((p<=20)) && l=""
			;;
      *) l=""
   esac
	#bat="$l <b>$p%</b>"
	bat="$l $p%"
}

get_ws(){
   ws=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3+1}')
	#out=("" "<b>$ws </b>")
}

t=5000
case_opt "$1"
