#!/usr/bin/env bash
xinput enable 'AT Translated Set 2 keyboard' && printf '%s' "enable" > "$HOME/.keylock"
if [[ $1 = suspend ]]; then
	env XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock -- systemctl suspend
else
	env XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock
fi
