#!/usr/bin/env bash

con-up() { nmcli c u "$1" | dunstify $_ ;}
con-down() { nmcli c d "$1" | dunstify $_ ;}

new-con(){
      ssid=$(nmcli -f SSID d w l | sed '/SSID/d;s/ *//g' |\
	 rofi -dmenu -i -p "[ new connection ]")
      [[ -z $ssid ]] && exit 0
      
      passwd=$(rofi -dmenu -p "[ passwd ]")
      [[ -z $passwd ]] && exit 0

      nmcli d w c "$ssid" password "$passwd"
}

del-con(){
   ans=$(printf '%s\n' "$con" | rofi -dmenu -i -p "[ delete connection ]")
   nmcli c d "$ans"
}

main() {
   con=$(nmcli -f NAME c s | sed '/NAME/d')
   active_con=$(nmcli -f NAME c s -a | sed '/NAME/d')
   active="[ active ] $active_con"
   new="[+] New Connection"
   del="[-] Delete Connection"

   [[ $active_con ]] && out=$(printf '%s\n' "${con/$active_con/$active}")
   out=$(printf '%s\n%s\n%s' "$out" "$new" "$del")
   ans=$(printf '%s\n' "$out" | rofi -dmenu -i -p "[ nmcli ]")

   case $ans in
      "$active") con-down $active_con ;;
      "$new") new-con ;;
      "$del") del-con ;;
      *) con-up $ans ;;
   esac
}

main "$@"
