#!/usr/bin/env bash

con-up() { echo conup; nmcli c u "$1" ;}
con-down() { echo condown; nmcli c dow "$1" ;}

new-con(){
	dunstify -t 10000 -r 202 "" "<b>nmcli searching.. please wait</b>"
	ssid=$(nmcli -f SSID d w l | sed '/SSID/d;s/ *//g')
	dunstify -C 202

	ans=$(echo "$ssid" | dmenu -i -b -fn "ypn envypn:size=14" -p "[ new connection ]")
	[[ $ans ]] || exit 0
      
	passwd=$(dmenu -b -fn "ypn envypn:size=14" -p "[ passwd ]")
	[[ $passwd ]] || exit 0

	nmcli d w c "$ssid" password "$passwd"
}

del-con(){
	ans=$(printf '%s\n' "$con" | dmenu -b -fn "ypn envypn:size=14" -i -p "[ delete connection ]" |\
      sed 's/\ *$//g')
	nmcli c de "$ans"
}

main() {
   con=$(nmcli -f NAME c s -o +a:-type | sed '/NAME/d;s/ *$//g')
   active_con=$(nmcli -f NAME c s -a | sed '/NAME/d;s/ *$//g')
	set $active_con
	active_con="$1"
   active="[ active ] $active_con"
   new="[+] New Connection"
   del="[-] Delete Connection"


   [[ $active_con ]] && con=$(printf '%s\n' "${con/$active_con/$active}")
   out=$(printf '%s\n%s\n%s' "$con" "$new" "$del")
   ans=$(printf '%s\n' "$out" | dmenu -i -b -fn "ypn envypn:size=14" -p "nmcli:")

   case $ans in
      "$active") con-down "${active_con}" ;;
      "$new") new-con ;;
      "$del") del-con ;;
      *) echo ${active_con%%\ lo*}; [[ $ans =~ ${active_con} ]] && con-down $active_con || con-up "$ans" ;;
   esac
}

main "$@"
