#!/usr/bin/env bash
# Måske lidt overgjort? 

selekt(){
   printf '%s' "Søger.."

   ((i=1))
   while read -r linje;do
      [[ $linje =~ ^$1:.* ]] && {

	 ssid_enkelt="${linje#"${linje%%[^$1:[:space:]*]*}"}"

	 space=""; ((i<10)) && space=" "
	 printf '\e[K\r%s%s\n' "$i: $space" "$ssid_enkelt"

	 declare -a ssid
	 IFS=$'\n' ssid+=($ssid_enkelt)

	 ((i++))
      }
   done < <(nmcli -f $1 -m multiline d w)

   read -rp "[1-$((i-1))]: "
   
   ((REPLY)) && ((a=REPLY-1))
   
   printf "${ssid[$a]}"
}

selekt SSID