#!/usr/bin/env bash

fz(){ fzf --ansi --height 40% --reverse "$@";}

editor(){ nvim +"set ft=markdown" "$@";}

new(){
   cd "$NOTES"
	mk_tmp
	editor +startinsert $tmp
	get_name
}

mk_tmp(){
	tmp="$(mktemp)"
   print_tags > $tmp
}

get_name(){
	while IFS= read -rsn1 -p $'\r\e[K'"name: ${input:-new_note}.md"$'\e[3D' char; do
		case "$char" in
			$'\177') input="${input%?}" ;;
			$'\015'|'') printf '\n'; break ;;
			" ") input+="_" ;;
			'	') match_items ;;
			*) input+="$char" ;;
		esac
	done
	mv "$tmp" "${input:-new_note}.md" -v -i
}

match_items(){
	test
}

edit(){
   note="$NOTES/$(print_notes | fz)"
   [[ -f "$note" ]] && editor "$note"
   exit 0
}

sync(){
   cd "$NOTES"
   status=$(git status --porcelain)
   [[ -z "$status" ]] && pull || push
}

show(){
   [[ "$NOTES" ]] && cd "$NOTES" || return 1
   tree -C
   printf '\e[1m%s\n\e[m%s\n' "entering subshell..." "ctrl+d to return"
	exec $SHELL
}

push(){
   git add .; git commit -m "$status"
   git push -u origin master
}

pull(){
   printf '%s\n' "No changes, checking remote.."
   git pull
}

print_notes(){
   IFS=$'\n' read -rd '' -a notes < <(fd -c always .md $NOTES)
   printf '%s\n' "${notes[@]#*${NOTES##*/}/}"
}

print_tags(){
   printf '\n\n%s\n%s' "[//]: # ($(date -Iseconds))" "[//]: # (tags: [<++>])"
}

print_opts(){
   opts=("new" "sync" "edit" "show")
   printf '%s\n' "${opts[@]}"
}

get_opts(){
   opt=$(print_opts | fz -0 -1 -q "$1")
   [[ $opt ]] || false
}

main(){
   get_opts $1 || exit
   eval $opt
}

main "$@"
