#!/usr/bin/env bash

get_id(){ id="$(xdotool search --class $cls)"; }
toggle(){ bspc node "$id" --flag hidden -f; exit; }

math(){
	cls="scratchmath"; get_id
	[[ -z "$id" ]] && { $TERMINAL -o "window.position: {x: 1000, y: 700}" -o "window.dimensions: {columns: 86, lines: 14}" --class $cls,$cls -e qalc; } || toggle
}

term(){
	cls="scratchterm"; get_id
	[[ -z "$id" ]] || toggle

	tmux has-session -t scratch &&
		{ $TERMINAL --class $cls,$cls -e tmux a -t '=scratch'; } ||
		{ $TERMINAL --class $cls,$cls -e tmux new -s 'scratch'; }
}

eval $1
