#!/usr/bin/env bash

fz(){ fzf --ansi --height 40% --reverse "$@";}

editor(){ nvim +"set ft=markdown" "$@";}

new(){
   cd "$SKOLE"
   #print_tags | editor +startinsert +"file new_note.md"
   editor +startinsert +"file new_note.md"
}

edit(){
   note="$SKOLE/$(print_notes | fz)"
   [[ -f "$note" ]] && editor "$note"
   exit 0
}

sync(){
   cd "$SKOLE"
   status=$(git status --porcelain)
   [[ -z "$status" ]] && pull || push
}

show(){
   [[ "$SKOLE" ]] && cd "$SKOLE" || return 1
   #tree -C
   printf '\e[1m%s\n\e[m%s\n' "entering subshell..."\
			  "ctrl+d to return"
	exec $SHELL
}

push(){
   git add .; git commit -m "$status"
   git push -u origin master
}

pull(){
   printf '%s\n' "No changes, checking remote.."
   git pull
}

print_notes(){
   IFS=$'\n' read -rd '' -a notes < <(fd -c always .md $SKOLE)
   printf '%s\n' "${notes[@]#*${SKOLE##*/}/}"
}

print_tags(){
   printf '\n\n%s\n%s' "[//]: # ($(date -Iseconds))"\
      "[//]: # (tags: [<++>])"
}

print_opts(){
   opts=("new" "sync" "edit" "show")
   printf '%s\n' "${opts[@]}"
}

get_opts(){
   opt=$(print_opts | fz -0 -1 -q "$1")
   [[ $opt ]] || false
}

main(){
   get_opts $1 || exit
   eval $opt
}

main "$@"
