#!/usr/bin/env bash

main(){
   dir=( "$HOME/.Scripts/" "$HOME/.bin/" )
   get_file && nvim "$HOME/$file"
}

get_file(){
   file=$(print_files | fz)
   [[ $file ]] || false
}

print_files(){
   files=($(fd -c always -d 1 -t x . "${dir[@]}" ))
   printf '%s\n' "${files[@]#*${HOME##*/}/}"
}

fz(){
   fzf --ansi -0 -1 -q "$query" --preview\
   "bat -l bash --theme='OneHalfDark'\
   --style=numbers,changes --color always $HOME/{}"
}

altfz(){
   fzf --ansi -0 -1 -q "$query" --preview\
   "$HOME/vimpager/vimcat -c AnsiEsc -c 'set ft=&ft' $HOME/{}"
}

query="$1"
main
