#!/usr/bin/env bash

main(){
   if [[ "$biggest" = "$focused" ]]
   then get_smaller
   else move_biggest; fi
}

read_leafs(){
   IFS=$'\n' read -r -d '' -a leafs <\
   <(bspc query -N -n .leaf.local.tiled)
}

query_nodes(){
   focused="$(bspc query -N -n focused.local)"
   biggest="$(bspc query -N -n biggest.local)"
}

get_smaller(){
   bspc node -s "${leafs[1]}"
   bspc node -f biggest.local
}

move_biggest(){
   bspc node -n biggest.local -s "${leafs[1]}"
   bspc node -s biggest.local --follow
}

read_leafs
query_nodes
main
