#!/usr/bin/env bash

confirm(){
	read -p "sure you want to kill ${proc_name//$HOME\//\~/} ($pid)? [y|N] "
	[[ "$REPLY" =~ y|Y ]] && echo $pid
}

main(){
   proc="$1"
	while read -r ps; do
		[[ "$ps" =~ $proc && ! "$ps" =~ ukill|vim ]] || continue
		[[ $opt = "grep" ]] && { echo $ps; exit; }
		set $ps
		pid=$1
		proc_name=$6
	done < <(ps ax)
	[[ $opt != "noconfirm" ]] && confirm
   #kill -$k "${p[0]}" && echo "[$p] killed" || exit 1
}

usage(){ printf '%s\n' "usage: ukill [-gnh] <script_name>"; exit 1; }

while getopts n:g:h a; do
	case $a in
		n) opt="noconfirm" ;;
		g) opt="grep" ;;
		h|help) usage
	esac
	shift
done

[[ $1 ]] || usage

main "$@"
