#!/usr/bin/env bash

confirm(){
	read -rp "sure you want to kill ${proc_name//$HOME\//\~/} ($pid)? [y|N] "
	[[ "$REPLY" =~ y|Y ]] || exit 0
}

main(){
   script_name="$1"
	while read -r ps; do
		[[ "$ps" =~ $script_name && ! "$ps" =~ ukill|vim ]] || continue
		[[ $opt = "grep" ]] && { echo $ps; exit 0; }
		set $ps
		pid=$1
		proc_name=$6
		kill_process
	done < <(ps ax)
}

kill_process(){
	[[ $opt = "noconfirm" ]] || confirm
   kill -9 "$pid" && echo "'$proc_name' killed" || exit 1
}

usage(){ printf '%s\n' "usage: ukill [-gnh] <script_name>"; exit 1; }

while getopts n:g:h a; do
	case $a in
		n) opt="noconfirm" ;;
		g) opt="grep" ;;
		h|help) usage
	esac
	shift
done

[[ $1 ]] || usage

main "$@"
