#!/usr/bin/env bash

on() {
   theme="base16-isotope"

   wal --theme $theme &>/dev/null

   source /home/ringdal/.cache/wal/colors.sh

   ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &
   #xsetroot -solid "$background"
   feh --bg-fill $HOME/Billeder/wallpapers/arch/black_arch.png &

   pkill dunst && dunst &>/dev/null & disown
   pkill compton; ukill dunstbar; ukill autogap

   for i in {1..10}; do
      bspc config -d $i left_padding 0
      bspc config -d $i right_padding 0
      #bsp-layout set tall $i
   done

   bspc config focused_border_color "$color6"
   bspc config normal_border_color "$color4"
   #bspc config initial_polarity first_child
   #bspc config automatic_scheme alternate
   [[ $(pgrep -f runbar) ]] && pkill -f runbar
   runbar -b & disown

   bspc config split_ratio 0.6

   border=2
   bspc config window_gap -$border
   bspc config border_width $border
   for side in top left right; do
      bspc config ${side}_padding $border
   done
   bspc config bottom_padding $((border+20))

   $CONFIG qute
}

off() {
   ukill runbar
   pkill lemonbar

   bspc config top_padding 0
   bspc config bottom_padding 0

   chwal -r

   "$CONFIG" &>/dev/null
   sleep .1
   echo > "$GAPFIFO" &
}

case $1 in on) on ;; off) off; esac
