#!/usr/bin/env bash

on() {
	wal --theme base16-isotope
	source /home/ringdal/.cache/wal/colors.sh

	xsetroot -solid "#000000"

	pkill picom
	ukill -k autogap

	for i in {1..10}; do
		bspc config -d $i left_padding 0
		bspc config -d $i right_padding 0
	done


	bspc config focused_border_color "$color4"
	bspc config presel_feedback_color "$color6"
	bspc config normal_border_color "#333333"
	#bspc config initial_polarity first_child
	#bspc config automatic_scheme alternate

	bspc config split_ratio 0.6
	bspc config single_monocle true

	border=1
	bspc config window_gap -$border
	bspc config border_radius $border
	bspc config border_width $border
	for side in top left right; do
		bspc config ${side}_padding $border
	done
	#bspc config bottom_padding $border

	#$CONFIG qute
	#eval $CONFIG
}

off() {
	bspc config top_padding 0
	bspc config bottom_padding 0
	for side in bottom top left right; do
		bspc config ${side}_padding 0
	done
	bspc config single_monocle false

	picom -b
	chwal -r

	#"$CONFIG" &>/dev/null
	sleep .1
	echo > "$GAPFIFO" &
}

case $1 in off) off ;; *) on; esac
