#!/usr/bin/env bash

usage(){ printf '%s\n' "Usage: wthr [-c <city>] [-sfl]"; exit 0; }

small(){
   wthr=$(printf '\n%s\n' "$wthr" |\
   sed -n 's/.*:/  /;2s/\,.*$//g;1,8p')
}

full(){ wthr=$(printf '%s\n' "$wthr" | head -38); }

wthr(){ printf '%s\n' "$wthr"; }

loop(){
   printf '\e[?25l\e[H\e[2J'; stty -echo
   for ((;;)) { wthr; sleep 60;}
}

main(){
   trap "printf '\e[?25h'; stty echo" EXIT
   wthr=$(curl --silent wttr.in)

   while getopts ":lsfc:" a; do
      case $a in
	 l) loop ;;
	 f) full ;;
	 s) small ;;
	 c) wthr="$(curl --silent wttr.in/$OPTARG)" ;;
	 ?|*) usage ;;
      esac
   done

   wthr
}

main "$@"
